### ISSUE TITLE
FastCopy340.zip and FastCopy340_x64.zip 404

### ISSUE THREAD

**Issue by technotherion** [2Shirt/WizardKit#11]
From ```.bin\Scripts\settings\sources.py```,

```
    'FastCopy32': 'http://ftp.vector.co.jp/69/76/2323/FastCopy340.zip',
    'FastCopy64': 'http://ftp.vector.co.jp/69/76/2323/FastCopy340_x64.zip',
```

Both URLs 404. Looks like they pulled the old URLs once 3.41 was released.

Here's the new URLs:
http://ftp.vector.co.jp/69/93/2323/FastCopy341.zip
http://ftp.vector.co.jp/69/93/2323/FastCopy341_x64.zip

**Comment by 2Shirt** [comment]
Fixed in dev branch with commit: 7d1826f
