### ISSUE TITLE
Suggested Arch Linux partition sizes

### ISSUE THREAD

**Issue by technotherion** [2Shirt/WizardKit#13]
I was building the UFD in Virtualbox and was wondering what kind of partition schematics are suggested for the Arch image, e.g. image size, size of the bootable partition, size of the swap partition. 

As an example, I created an 8gb Arch image. How would you suggest formatting it?

**Comment by 2Shirt** [comment]
You need around 6Gb of free space as it says in the readme. I would use
ext4 for the file system since we don’t need anything fancy for the
development environment. Please refer to the installation guide on the
ArchLinux Wiki for general installation instructions.
