### ISSUE TITLE
"./Build\ Linux -b" quits without error

### ISSUE THREAD

**Issue by technotherion** [2Shirt/WizardKit#14]
Followed Arch Wiki install instructions, created a user, added user to sudoers, and get to the Build Linux phase. ```./Build\ Linux -b``` returns no info, instantly finishes/quits. Adding sudo merely gives me an error that it's not meant to be run as sudo. 

Here's what else I tried: 

```sudo ./Build\ Linux -f``` works as expected, changes permissions
```./Build\ Linux -i``` installs dependencies as expected.
```./Build\ Linux -o``` fails because '/WizardKit/BUILD_LINUX/main.py' not found
```./Build\ Linux -p``` fails because '/WizardKit/BUILD_LINUX/main.py' not found
```./Build\ Linux -u``` completes successfully

**Comment by 2Shirt** [comment]
1. Did you use git to clone the repo?
2. What is the full path to the repo in the VM?

**Comment by technotherion** [comment]
1. Yes.
2. /Wizardkit. Will try moving to /home/user/Wizardkit and try again.

**Comment by 2Shirt** [comment]
I just finished building a kit in a new VM so I think that you're download was incomplete or that the permissions are messed up.

I recommend that you remove the WizardKit folder and start over by cloning the repo in the home folder.

**Comment by technotherion** [comment]
Looks like it definitely was an incomplete download of some sort.

Going to let the script run; if it completes successfully I'll close the issue.
