### ISSUE TITLE
SMART and Badblocks script unable to detect USB drives.

### ISSUE THREAD

**Issue by technotherion** [2Shirt/WizardKit#8]
Steps to replicate:

1. use ```mount-all-drives``` to verify that USB drive(s) are indeed attached.
2. hit super+s to open SMART or super+d (option 3)
3. No USB drives will be detected, but HDDs will be detected as usual. 

Tested with: 
Two separate thumb drives
One shop system

When available, will test with a separate system.

**Comment by 2Shirt** [comment]
I will enable testing for all devices except those labeled "${KIT_NAME_SHORT}_LINUX"
I would prefer to enable testing for non-hotplug devices and external HDDs excluding all UFDs, card readers, etc.

**Comment by 2Shirt** [comment]
Closing issue; however, I may address this again in the future.
